repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4  # Use the latest version
    hooks:
      - id: ruff  # Linter
      - id: ruff-format  # Formatter (optional)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespace
      - id: end-of-file-fixer  # Ensures files end with a newline
      - id: check-yaml  # Validates YAML files
      - id: check-json  # Validates JSON files

  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest version
    hooks:
      - id: black  # Python code formatter
