services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"   # HTTP Interface
      - "9000:9000"   # Native Client Interface (used by dbt-clickhouse)
      - "9009:9009"   # Internal replication (if needed)
    env_file:
      - .env
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data:
    driver: local
